USE [master]
GO

/****** Object:  Database [wtfbook]    Script Date: 2015/3/10 PM 04:10:26 ******/
DROP DATABASE [wtfbook]
GO

/****** Object:  Database [wtfbook]    Script Date: 2015/3/10 PM 04:10:26 ******/
CREATE DATABASE [wtfbook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'wtfbook', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\wtfbook.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'wtfbook_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\wtfbook_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [wtfbook] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [wtfbook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [wtfbook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [wtfbook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [wtfbook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [wtfbook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [wtfbook] SET ARITHABORT OFF 
GO

ALTER DATABASE [wtfbook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [wtfbook] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [wtfbook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [wtfbook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [wtfbook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [wtfbook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [wtfbook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [wtfbook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [wtfbook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [wtfbook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [wtfbook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [wtfbook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [wtfbook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [wtfbook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [wtfbook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [wtfbook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [wtfbook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [wtfbook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [wtfbook] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [wtfbook] SET  MULTI_USER 
GO

ALTER DATABASE [wtfbook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [wtfbook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [wtfbook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [wtfbook] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [wtfbook] SET  READ_WRITE 
GO

